### PR TITLE
added an AI/ML project idea

### PR DESCRIPTION
**Pull request by Gautam1302**
Added AI ML Project Idea.

### CODE REVIEW

**Review by praveenscience — APPROVED** [review]
👍

**Comment by praveenscience** [comment]
@Gautam1302 Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.

**Comment by Gautam1302** [comment]
yes sir i have already subscribed . sir i wanted to know which editor do you use to edit readme .

**Comment by praveenscience** [comment]
I use the Web Editor only. But I will suggest you to use Typora.io.

Also, it's called BlockQuote.

```text
> _Text here._
```

The above code will become:

> _Text here._

Have a nice day. Let me know if you have any more questions. Thanks again.

**Comment by Gautam1302** [comment]
thanku :)

**Pull request merged**
