### PR TITLE
Adds React and Python Projects.

### PR DESCRIPTION
**Pull request by Ashish1323**

### CODE REVIEW

**Comment by praveenscience** [comment]
Can you please fix the merge conflicts?

**Comment by Ashish1323** [comment]
> Can you please fix the merge conflicts?

Yeah, it's updated now, please merge the changes and let me know if there is an issue.

**Review by praveenscience — APPROVED** [review]
LGTM 👍

**Comment by praveenscience** [comment]
@Ashish1323 Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.

**Pull request merged**
